name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  dio: ^5.7.0
  shared_preferences: ^2.3.4
  dartz: ^0.10.1
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/ReadexPro-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/ReadexPro-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/ReadexPro-Medium.ttf
  #         weight: 500
  #       - asset:  assets/fonts/ReadexPro-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #         weight: 900
  #       - asset: assets/fonts/ReadexPro-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/SF-Pro-Display-Regular.ttf
  #         weight: 800
